// Bake the probe phrases into vectors: `pnpm probes`.
//
// Runs the same embedder the browser would, here, once, so that no buyer ever
// downloads a model to see the front page. Output is src/geometry/probe-vectors.js —
// sixteen 344-char strings, ~6 KB, in the main bundle.
//
// Re-run this whenever PROBES changes, or when embed.js changes model or dim:
// the stamp written here is what probes.js checks before trusting a vector, so a
// stale bake disables the curated rows instead of ranking against noise.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { EMBED_DIM, EMBED_MODEL, embedQuery, packVec } from "../src/llm/embed.js";
import { PROBES } from "../src/geometry/probes.js";

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "probe-vectors.js");

const vecs = {};
for (const p of PROBES) {
    process.stdout.write(`  ${p.id}…`);
    vecs[p.id] = packVec(await embedQuery(p.text));
    process.stdout.write(" ok\n");
}

const body = Object.entries(vecs).map(([id, v]) => `        ${JSON.stringify(id)}: ${JSON.stringify(v)},`).join("\n");
writeFileSync(out, `// GENERATED by \`pnpm probes\` (scripts/bake-probes.js) — do not edit by hand.
// Probe phrases from probes.js, embedded as queries and packed to base64 int8.
// Re-run the bake after changing PROBES, the model, or the dim.
export default {
    model: ${JSON.stringify(EMBED_MODEL)},
    dim: ${EMBED_DIM},
    vecs: {
${body}
    },
};
`);

console.log(`baked ${PROBES.length} probes → ${out}`);
